# Generated by Django 5.2.3 on 2025-09-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('blusa', 'Blusa'), ('pantalon', 'Pantalón'), ('falda', 'Falda'), ('vestido', 'Vestido'), ('calzado', 'Calzado'), ('accesorio', 'Accesorio')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
