# Generated by Django 5.2.8 on 2025-11-20 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_tone', models.CharField(choices=[('claro', 'Claro'), ('medio', 'Medio'), ('oscuro', 'Oscuro')], default='medio', max_length=10)),
                ('style_preferences', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('deportivo', 'Deportivo'), ('bohemio', 'Bohemio')], default='casual', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
