# Generated by Django 5.2.8 on 2025-11-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('blusa', 'Blusa'), ('pantalon', 'Pantalón'), ('falda', 'Falda'), ('vestido', 'Vestido'), ('calzado', 'Calzado'), ('accesorio', 'Accesorio'), ('outfit_completo', 'Outfit Completo')], max_length=20),
        ),
    ]
